### ISSUE TITLE
Compatibility with Ruby 1.9.2

### ISSUE THREAD

**Issue by tpberntsen** [ruport/ruport#14] opened 2011-12-01 19:58 UTC
Hi,

Thanks for a great gem.

I've read in another post that you're working on a 1.9.2 compatible version, which would be absolutely fantastic to have.

Are you still working on it, and if so, when do you then expect to release it?

Cheers,
Thomas

**Comment by kbrock** [comment] 2020-06-25 03:53
duplicate of #28 
Rupport is now supporting all currently supported versions of ruby.

**Closed by kbrock** 2020-06-25 03:53 UTC
